version: '3.8'

services:
  fridger-main:
    container_name: fridger-main
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: local
    ports:
      - '1805:80'
    volumes:
      - ./app/src:/var/www/app/src
      - ./app/config:/var/www/app/config
      - ./app/vendor:/var/www/app/vendor
      - ./app/var:/var/www/app/var
      - ./app/.env:/var/www/app/.env
