version: '3.8'

services:
  fridger-main:
    container_name: fridger-main
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: local
    ports:
      - '1805:80'
    volumes:
      - ./app:/var/www/app/
      - ./docker/php/local/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini

  fridger-db:
    container_name: fridger-db
    image: postgres:13.3
    environment:
      POSTGRES_DB: fridger
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - fridger-db-storage:/var/lib/postgresql/data

volumes:
  fridger-db-storage:
    driver: local
