version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
    environment:
      APP_ENV: prod
    ports:
      - '1805:80'
