doctrine:
    dbal:
        driver: 'pdo_pgsql'
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '13.3'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Model/User'
                prefix: 'App\Core\Component\UserManagement\Domain\Entity'
                alias : User
            Tag:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Model/Tag'
                prefix: 'App\Core\Component\CookingBook\Domain\Entity\Tag'
                alias: Tag
            Ingredient:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Model/Ingredient'
                prefix: 'App\Core\Component\CookingBook\Domain\Entity\Ingredient'
                alias: Ingredient
            Recipe:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Model/Recipe'
                prefix: 'App\Core\Component\CookingBook\Domain\Entity'
                alias: Recipe
            RecipeIngredient:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Model/RecipeIngredient'
                prefix: 'App\Core\Component\CookingBook\Domain\Entity\RecipeIngredient'
                alias: RecipeIngredient
