framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
             command: 'sync://'
             query: 'sync://'

        routing:
            # Route your messages to the transports
             'App\Core\Component\UserManagement\Application\Write\Command\CreateUserCommand': command
             'App\Core\Component\UserManagement\Application\Write\Command\CreateAdminCommand': command
             'App\Core\Component\UserManagement\Application\Read\Query\RetrieveUsersQuery': query
             'App\Core\Component\UserManagement\Application\Read\Query\RetrieveUserDataQuery\RetrieveUserDataQuery': query
             'App\Core\Component\CookingBook\Application\Write\Command\CreateTagCommand\CreateTagCommand': command
             'App\Core\Component\CookingBook\Application\Write\Command\CreateIngredientCommand\CreateIngredientCommand': command
             'App\Core\Component\CookingBook\Application\Read\Query\RetrieveIngredientsQuery\RetrieveIngredientsQuery': query
