framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
             sync: 'sync://'

        routing:
            # Route your messages to the transports
             'App\Core\Component\UserManagement\Application\Write\Command\CreateUserCommand': sync
             'App\Core\Component\UserManagement\Application\Write\Command\CreateAdminCommand': sync
             'App\Core\Component\UserManagement\Application\Read\Query\RetrieveUsersQuery': sync
             'App\Core\Component\CookingBook\Application\Write\Command\CreateTagCommand\CreateTagCommand': sync
